%% NAME Test

IDENTIFIER
    = !KEYWORD [A-Za-z_] ([A-Za-z0-9_])* SKIP
    ;

SKIP = WHITESPACE* ;

WHITESPACE
    = [ \n]
    | LINE_COMMENT
    ;

LINE_COMMENT
    = '//' ![!/] (!'\n' .)*
    | '////' (!'\n' .)* 
    ;

END_OF_WORD = ![a-zA-Z0-9_] SKIP;
KEYWORD_ADDRSPACE   = 'addrspace'   END_OF_WORD ;
KEYWORD_ALIGN       = 'align'       END_OF_WORD ;
KEYWORD_ALLOWZERO   = 'allowzero'   END_OF_WORD ;
KEYWORD_AND         = 'and'         END_OF_WORD ;
 
KEYWORD = KEYWORD_ADDRSPACE | KEYWORD_ALIGN | KEYWORD_ALLOWZERO | KEYWORD_AND
         ;
